var teamData = [
  {
    "address": null, 
    "city": "O Fallon", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc1094", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Hooked on Technology", 
    "name": "The Boeing Company/Boeing Employees Community Fund/Nidec Motor Corporation/Cuivre River Electrical Coop/Toyota/Unisys/Ameren Missouri/Missouri State Technical College&River City Robots", 
    "nickname": "Channel Cats", 
    "postal_code": "63366", 
    "rookie_year": 2003, 
    "state_prov": "Missouri", 
    "team_number": 1094, 
    "website": "http://channelcats.rivercityrobots.org/"
  }, 
  {
    "address": null, 
    "city": "Iowa City", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc167", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "SPRING (Students Promoting Robotics and Inspiring New Generations) Into Action!", 
    "name": "Rockwell Collins/Aero Antenna Technology & Iowa City High School & West Senior High School", 
    "nickname": "Children of the Corn", 
    "postal_code": "52246", 
    "rookie_year": 1998, 
    "state_prov": "Iowa", 
    "team_number": 167, 
    "website": "http://www.icrobotics.org"
  }, 
  {
    "address": null, 
    "city": "Olathe", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc1710", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "We don't just build robots, we build leaders.", 
    "name": "Clay Blair Family Foundation/Ewing Kauffman Foundation/US Engineering/Black & Veatch/EW Plumbing/Society of Women Engineers-Exxon Mobil Corporation/Farmers Insurance/Olathe Public Schools/Top Notch Heating and Cooling/Peoples State Bank/Sherman Family Foundation/Reproductive Resource Center/Rockwell Automation/Imagine Dental&Olathe Northwest High School", 
    "nickname": "The Ravonics Revolution", 
    "postal_code": "66061", 
    "rookie_year": 2006, 
    "state_prov": "Kansas", 
    "team_number": 1710, 
    "website": "http://www.team1710.com"
  }, 
  {
    "address": null, 
    "city": "Shawnee", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc1982", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "BlueScope Construction/Shawnee Mission Education Foundation/Garmin/Cruise & Shawnee Mission Northwest High", 
    "nickname": "Cougar Robotics", 
    "postal_code": "66216", 
    "rookie_year": 2007, 
    "state_prov": "Kansas", 
    "team_number": 1982, 
    "website": "http://www.nwcougarrobotics.com"
  }, 
  {
    "address": null, 
    "city": "Florissant", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc1985", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Monsanto Fund/The Boeing Company/Hazelwood School District /Davlan Engineering&Hazelwood Central High", 
    "nickname": "Robohawks", 
    "postal_code": "63031", 
    "rookie_year": 2007, 
    "state_prov": "Missouri", 
    "team_number": 1985, 
    "website": "http://www.robohawks1985.org"
  }, 
  {
    "address": null, 
    "city": "Overland Park", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc2410", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Do what you love; love what you do. Work hard for others; they'll do that for yo", 
    "name": "Blue Valley Educational Foundation/General Motors/Honeywell/Ryerson/Hantover&Blue Valley Center For Professional Studies", 
    "nickname": "Blue Valley CAPS Metal Mustang Robotics", 
    "postal_code": "66223", 
    "rookie_year": 2008, 
    "state_prov": "Kansas", 
    "team_number": 2410, 
    "website": "http://www.mmr2410.com/"
  }, 
  {
    "address": null, 
    "city": "Minneapolis", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2500", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Together, we WILL\u00a0build a new heroic future", 
    "name": "Coloplast/Boston Scientific/General Mills/The Bakken Museum/EJ Ajax & Sons Inc./Medtronic/NASA/St. Thomas University/Carlson Advisors LLP/Install This Sign and Awning Co./Loram/Girl Scouts of Minnesota and Wisconsin River Valleys/Shingle Creek Neighborhood Association/Saint Thomas University- Engineering Department/Minneapolis Public Schools Career and Technical Education/Dunwoody College of Technology/Patrick Henry High School Booster Club/GOFIRST/Patrick Henry High School Foundation&Henry Senior High", 
    "nickname": "Herobotics", 
    "postal_code": "55412", 
    "rookie_year": 2008, 
    "state_prov": "Minnesota", 
    "team_number": 2500, 
    "website": "http://heroboticsteam.moonfruit.com/"
  }, 
  {
    "address": null, 
    "city": "Osseo", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2526", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Boston Scientific/TURCK Inc./Twin Cities Fan Companies, Ltd./Aloft Technologies Inc/BKBM Engineers/NTI/Nvidia/ICA Corporation/Accorde Orthodontists/Allegra Printing Brooklyn Park/Tennant/Pinnacle Engineering/Entrust Datacard/Solos Pizza Cafe/Three Squares Restaraunt/Chipotle/Natur-Bag/Alchemy Mfg./Hitesman & Wold PA/Youngstedts Maple Grove Tire and Auto/Mobile Veterinary Ultrasound/Rush Creek Golf Club/World Taekwando Academy-Osseo/Dunkirk Dental/Osseo Lions Club/Maple Grove Lions Club/Rita's Italian Ice/Avallo Marketing/Legato Industries Inc&Maple Grove Senior High&Family/Community", 
    "nickname": "Crimson Robotics", 
    "postal_code": "55369", 
    "rookie_year": 2008, 
    "state_prov": "Minnesota", 
    "team_number": 2526, 
    "website": "http://www.crimsonrobotics.com/"
  }, 
  {
    "address": null, 
    "city": "Minneapolis", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2549", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Humans are so Last Year", 
    "name": "Best Buy INC - Head Quarters/Best Buy&Washburn Senior High", 
    "nickname": "Millerbots", 
    "postal_code": "55419", 
    "rookie_year": 2008, 
    "state_prov": "Minnesota", 
    "team_number": 2549, 
    "website": "http://www.washburnmillerbots.com/"
  }, 
  {
    "address": null, 
    "city": "Grain Valley", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc2874", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Together we can!", 
    "name": "Honeywell FM&T/DeHaan Remodeling/Absolute Automotive/May Technology & Mfg. Inc/Schefers Roofing/Grain Valley High School/Jeff Grisham/Lunar Bowl/Elkins Heating and Cooling/Emmert Welding&Grain Valley High", 
    "nickname": "Iron Eagles", 
    "postal_code": "64029", 
    "rookie_year": 2009, 
    "state_prov": "Missouri", 
    "team_number": 2874, 
    "website": "http://"
  }, 
  {
    "address": null, 
    "city": "Alden", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2957", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Medtronic, Inc./Innovance Inc/Alden-Conger Robotic Team/Arnold's &Alden-Conger Secondary", 
    "nickname": "Knights", 
    "postal_code": "56009", 
    "rookie_year": 2009, 
    "state_prov": "Minnesota", 
    "team_number": 2957, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Farmington", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc2987", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Twin Cities Business/UTC Aerospace Systems/General Dynamics&Farmington High School", 
    "nickname": "Rogue Robotics", 
    "postal_code": "55024", 
    "rookie_year": 2009, 
    "state_prov": "Minnesota", 
    "team_number": 2987, 
    "website": "http://roguerobotics.wixsite.com/frc2987"
  }, 
  {
    "address": null, 
    "city": "Delano", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc3026", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Sil-Pro/Griffith Machine Works/Loretto Lions Club/Eaton/Industrial Louvers/Delano Lions Club/Norwesco/GT Engineering/Industrial Supply Company&Delano Senior High", 
    "nickname": "Orange Crush Robotics", 
    "postal_code": "55328", 
    "rookie_year": 2009, 
    "state_prov": "Minnesota", 
    "team_number": 3026, 
    "website": "http://www.ocr3026.com/"
  }, 
  {
    "address": null, 
    "city": "Woodbury ", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc3206", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Thou Shalt Not Play Minecraft", 
    "name": "3M / Northern Tier / Woodbury Rotary Club / Harvey Vogel / Silver Bullet / Medtronic / Xcel Energy / Gerdau & Woodbury Senior High", 
    "nickname": "Royal T-Wrecks", 
    "postal_code": "55125", 
    "rookie_year": 2010, 
    "state_prov": "Minnesota", 
    "team_number": 3206, 
    "website": "http://www.royaltwrecks.org/"
  }, 
  {
    "address": null, 
    "city": "Onalaska", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4021", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "LHI/Mathy Construction/Ingersoll Rand & Luther High School & Seven Rivers Robotics Coalition", 
    "nickname": "igKnightion", 
    "postal_code": "54650-3142", 
    "rookie_year": 2012, 
    "state_prov": "Wisconsin", 
    "team_number": 4021, 
    "website": "http://www.igKnightion.com"
  }, 
  {
    "address": null, 
    "city": "La Crosse", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4054", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Logistics Health/Mathy Construction/Ace of LaCrosse/LaCrosse glass and overhead door/Dahl Automotive & Central High", 
    "nickname": "Robo Raiders", 
    "postal_code": "54601", 
    "rookie_year": 2012, 
    "state_prov": "Wisconsin", 
    "team_number": 4054, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Blue Earth Area", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4260", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Medtronics/jcpenney & Blue Earth Area Senior High", 
    "nickname": "BEAR Bucs", 
    "postal_code": "56013", 
    "rookie_year": 2012, 
    "state_prov": "Minnesota", 
    "team_number": 4260, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Saint Paul", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4506", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "3M/Motion Tech Automation/Reiling Construction/Brigid O'Malley&Hill Murray School", 
    "nickname": "PioNerds", 
    "postal_code": "55109", 
    "rookie_year": 2013, 
    "state_prov": "Minnesota", 
    "team_number": 4506, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Owatonna", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4624", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Bosch/ISD 761 Foundation Grant/American Legion Post #77/R & K Electric/Wenger/Apex Painting/Amesbury TRUTH/Federated Insurance&Owatonna Senior High", 
    "nickname": "Rebel Alliance", 
    "postal_code": "55060", 
    "rookie_year": 2013, 
    "state_prov": "Minnesota", 
    "team_number": 4624, 
    "website": "http://owatonna4624.wixsite.com/4624"
  }, 
  {
    "address": null, 
    "city": "West Fargo", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc4818", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "John Deere/Microsoft/North Dakota Space Grant Consortium/Scheels/Otter Tail Power/ND CTE Dept/Packer Backers/Molex/Diamond J Customs/JDP Automation/PTC/Butler/Cook Endodontics/Brenco Cleaning Equimpent/Midwest Coating Inc/BTD Custom Metal Work/Bell State Bank and Trust/Houston Engineering/SAE North Central Section/Ostroms Ace Hardware/Fargo 3D Printing/Gadget Garage/AIC Maintenance/Trail King Industries/Sanford Health/FM Engineers Club/Agassiz Chemical & Equipment/McNeilus Steel/FM Home and Patio/High Point Networks/Fargo Automation&West Fargo High School", 
    "nickname": "The Herd", 
    "postal_code": "58078", 
    "rookie_year": 2013, 
    "state_prov": "North Dakota", 
    "team_number": 4818, 
    "website": "http://wfrobotics.org"
  }, 
  {
    "address": null, 
    "city": "Prairie Grove", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "Houston", 
      "2018": "Houston"
    }, 
    "key": "frc5006", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "RCAL Products Inc.&Haas Hall Academy", 
    "nickname": "Apophis", 
    "postal_code": "72753", 
    "rookie_year": 2014, 
    "state_prov": "Arkansas", 
    "team_number": 5006, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "West Branch", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5041", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Designing Robots, Building Leaders", 
    "name": "Monsanto Fund/Rockwell Collins/Hoffman Family/Hoover Presidential Library/Twinkle Co&West Branch High School", 
    "nickname": "CyBears", 
    "postal_code": "52358", 
    "rookie_year": 2014, 
    "state_prov": "Iowa", 
    "team_number": 5041, 
    "website": "https://5041cybearrobotics.wordpress.com/"
  }, 
  {
    "address": null, 
    "city": "Cedar Falls", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc525", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Students Working Around Robotic Technology", 
    "name": "Cedar Falls Community Schools/John Deere/PTC/Rockwell Collins/Denso International America, Inc./Iowa State University College of Engineering/DISTek Integration, Inc/Hawkeye Tool and Die&Cedar Falls High School", 
    "nickname": "Swartdogs", 
    "postal_code": "50613", 
    "rookie_year": 2001, 
    "state_prov": "Iowa", 
    "team_number": 525, 
    "website": "http://www.525swartdogs.org"
  }, 
  {
    "address": null, 
    "city": "Shakopee", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5541", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "fortuna tironibus", 
    "name": "Amazon Fulfillment/Emerson/Bayer/Entrust Datacard/KEB/TORO&Shakopee Senior High", 
    "nickname": "Shakopee Robotics", 
    "postal_code": "55379", 
    "rookie_year": 2015, 
    "state_prov": "Minnesota", 
    "team_number": 5541, 
    "website": "http://www.shakopeerobotics.org"
  }, 
  {
    "address": null, 
    "city": "Spirit Lake", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5576", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Spirit Lake High School", 
    "nickname": "Team Terminator", 
    "postal_code": "51360", 
    "rookie_year": 2015, 
    "state_prov": "Iowa", 
    "team_number": 5576, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Waterloo", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5837", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "We work for TiPS", 
    "name": "John Deere/Denso/Iowa Governor's STEM Advisory Council & West High School & East High School", 
    "nickname": "Unity4Tech", 
    "postal_code": "50703", 
    "rookie_year": 2016, 
    "state_prov": "Iowa", 
    "team_number": 5837, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Bennington", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5906", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "&Bennington Secondary School", 
    "nickname": "Titanium Badgers", 
    "postal_code": "68007", 
    "rookie_year": 2016, 
    "state_prov": "Nebraska", 
    "team_number": 5906, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Caledonia", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5914", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Coopertition", 
    "name": "Mathy Construction Co./Acentek/American Legion Post #191/Joe Welch Equipment/Seven Rivers Region Coalition/Caledonia Haulers/Masonic Lodge/Konkel Wood Products/Hoskins Electric/Merchant Bank/Fastenal/Caledonia Lions/Brownsville Lions/Eitzen Lions/Sir Lancersir Bots #2977/Just Stitch it, Meisch Upholstery/Miken Sports/Kids Corner & Spring Grove Secondary & Caledonia Senior High", 
    "nickname": "Caledonia Robotic Warriors", 
    "postal_code": "55921", 
    "rookie_year": 2016, 
    "state_prov": "Minnesota", 
    "team_number": 5914, 
    "website": "http://cps.k12.mn.us/page/3841"
  }, 
  {
    "address": null, 
    "city": "Grinnell", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5935", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Iowa Governor's STEM Advisory Council/Grinnell-Newburg Community School District/Grinnell Mutual Reinsurance Company/Image First Signs/Pagliai's Italian Pizza/West Side Diner Family Restaurant/Grinnell Realty/Sumner Tree Service & Grinnell Community Senior High School", 
    "nickname": "Tech Tigers", 
    "postal_code": "50112", 
    "rookie_year": 2016, 
    "state_prov": "Iowa", 
    "team_number": 5935, 
    "website": "http://ghstechtigers.weebly.com/"
  }, 
  {
    "address": null, 
    "city": "Westbrook", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc5991", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Highwater Ethanol Plant/Meadowland Farmers Coop/John Valentine/Wendorff Welding/State Farm /FIRST Robotics/Medtronics&Westbrook-Walnut Grove Secondary", 
    "nickname": "Chargers", 
    "postal_code": "56183", 
    "rookie_year": 2016, 
    "state_prov": "Minnesota", 
    "team_number": 5991, 
    "website": "http://www.firstinspires.org/"
  }, 
  {
    "address": null, 
    "city": "Istanbul", 
    "country": "Turkey", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "Houston", 
      "2018": "Houston"
    }, 
    "key": "frc6025", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Bahcesehir Anatolian Highschool", 
    "nickname": "Adroit Androids", 
    "postal_code": "34538", 
    "rookie_year": 2016, 
    "state_prov": "Istanbul", 
    "team_number": 6025, 
    "website": "http://team6025.com/"
  }, 
  {
    "address": null, 
    "city": "Dike", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6164", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Monsanto /Iowa Governor's STEM Advisory Council/John Deere/FRC-First Robotics Competition/COMMUNITY FOUNDATION OF NORTHEAST IOWA/Mike Albers Construction/Yellow Jacket Enterprises, LLC/Dike-New Hartford CSD&Dike-New Hartford High School", 
    "nickname": "Moonshot Slaybots", 
    "postal_code": "50624", 
    "rookie_year": 2016, 
    "state_prov": "Iowa", 
    "team_number": 6164, 
    "website": "http://dnhrobotics.weebly.com/"
  }, 
  {
    "address": null, 
    "city": "Davenport", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6317", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "John Deere/NASA/STEM Innovators/Davenport Community School District/Scale-Up&West High School", 
    "nickname": "Disruptive Innovation", 
    "postal_code": "52804", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6317, 
    "website": "https://davenportwest.github.io/6317/"
  }, 
  {
    "address": null, 
    "city": "Manchester", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6320", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Iowa Governor's STEM Advisory Council/Royal Alliance Monaghan Financial Services, LTD. /Maquoketa Valle Coop/Loecke Building Services/Simon's Feed/Regional Medical Center/FIRST&West Delaware High School", 
    "nickname": "Iron Hawks", 
    "postal_code": "52057", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6320, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Aurora", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6359", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "NASA & Family/Community", 
    "nickname": "TechKnow Difficulties", 
    "postal_code": "68818", 
    "rookie_year": 2017, 
    "state_prov": "Nebraska", 
    "team_number": 6359, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Spencer", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6371", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Iowa Governor's STEM Advisory Council/Spencer Community School District&Spencer High School", 
    "nickname": "Spencer Robotics", 
    "postal_code": "51301", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6371, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Pleasant Hill", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6379", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "John Deere&Southeast Polk High School", 
    "nickname": "Terabyte of Ram", 
    "postal_code": "50327", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6379, 
    "website": "https://sites.google.com/a/southeastpolk.org/southeast-polk-first-robotics-competition/"
  }, 
  {
    "address": null, 
    "city": "West Des Moines", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6419", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "NASA/Iowa Governor's STEM Advisory Council/John Deere/Scrum Tzu/West Des Moines Community Schools/City of West Des Moines & Valley High School", 
    "nickname": "Innovation, Collaboration, and Excellence", 
    "postal_code": "50265", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6419, 
    "website": "http://www.IowaICE.org"
  }, 
  {
    "address": null, 
    "city": "Muscatine", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6420", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "NASA/Iowa Governor's STEM Advisory Council/Monsanto/John Deere/HNI Corporation -- Hon and Allsteel/Community Foundation of Greater Muscatine (CFGM)/TEAM Staffing Solutions/Hoffmann Inc./Kent Corporation&Muscatine High School", 
    "nickname": "Fire Island Robotics", 
    "postal_code": "52761", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6420, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Waterloo", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6455", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "NASA & Columbus High School", 
    "nickname": "The Coded Collective", 
    "postal_code": "50701", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6455, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Lenox", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6467", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Lenox High School", 
    "nickname": "Tiger Robotics", 
    "postal_code": "50851", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6467, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Vinton", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6536", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "West High School", 
    "nickname": "TheDarkSide", 
    "postal_code": "52349", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6536, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "La Porte City", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6630", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "John Deere/FIRST/Iowa Governor's STEM Advisory Council&Union High School", 
    "nickname": "F.U.N.  (FieRCely Uknighted Nation)", 
    "postal_code": "50651", 
    "rookie_year": 2017, 
    "state_prov": "Iowa", 
    "team_number": 6630, 
    "website": "http://6630fun.weebly.com/"
  }, 
  {
    "address": null, 
    "city": "Bloomfield", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6889", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Davis County Community High School", 
    "nickname": "Davis County", 
    "postal_code": "52537", 
    "rookie_year": 2018, 
    "state_prov": "Iowa", 
    "team_number": 6889, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Stuart", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc6950", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "West Central Valley High School", 
    "nickname": "West Central Valley TAG", 
    "postal_code": "50250", 
    "rookie_year": 2018, 
    "state_prov": "Iowa", 
    "team_number": 6950, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Sinop", 
    "country": "Turkey", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "Houston", 
      "2018": "Houston"
    }, 
    "key": "frc6999", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Sinop Bilim ve Sanat Merkezi", 
    "nickname": "B.E.S.T.", 
    "postal_code": "57000", 
    "rookie_year": 2018, 
    "state_prov": "Sinop", 
    "team_number": 6999, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Bolzano", 
    "country": "Italy", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": null, 
    "key": "frc7012", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Istituto Rainerum Bolzano", 
    "nickname": "Rainerum Robotics", 
    "postal_code": "39100", 
    "rookie_year": 2018, 
    "state_prov": "Bolzano", 
    "team_number": 7012, 
    "website": null
  }, 
  {
    "address": null, 
    "city": null, 
    "country": null, 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": null, 
    "key": "frc7122", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": null, 
    "nickname": "Central Campus (final name to be determined later)", 
    "postal_code": "50309", 
    "rookie_year": 2018, 
    "state_prov": null, 
    "team_number": 7122, 
    "website": null
  }, 
  {
    "address": null, 
    "city": "Saint Louis", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Houston"
    }, 
    "key": "frc931", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": "Explore Robotics", 
    "name": "Ranken Technical College/Boeing/Rockwell Automation/Shapiro Supply/Verizon/Belleville Kiwanis/WaterJet Tech/Bates Sales/Ethical Society/Monsanto/Copper Bend Pharmacy/Hartwig, Inc./Tech Manufacturing/Saint Louis Public Schools&Gateway High", 
    "nickname": "Perpetual Chaos", 
    "postal_code": "63110", 
    "rookie_year": 2002, 
    "state_prov": "Missouri", 
    "team_number": 931, 
    "website": "http://www.slps.org/domain/7813"
  }, 
  {
    "address": null, 
    "city": "Marion", 
    "country": "USA", 
    "gmaps_place_id": null, 
    "gmaps_url": null, 
    "home_championship": {
      "2017": "St. Louis", 
      "2018": "Detroit"
    }, 
    "key": "frc967", 
    "lat": null, 
    "lng": null, 
    "location_name": null, 
    "motto": null, 
    "name": "Rockwell Collins/Linn-Mar Booster Club/EHA/Iowa Fluid Power/Lindahl Marine Contractors, Inc./Linn-Mar Foundation/Conveyor Engineering/Bentley Manufacturing/Master Tool Mfg/D.A.D. Mfg Inc/Cargill/Verizon/Intermec/Linn County REC/CIPCO/McElroy Trust & Linn-Mar High School", 
    "nickname": "Iron Lions", 
    "postal_code": "52302", 
    "rookie_year": 2002, 
    "state_prov": "Iowa", 
    "team_number": 967, 
    "website": "http://www.lmrobotics.com"
  }
]